### ISSUE TITLE
ENH: n_iter is often 0 when using strong WS

### ISSUE THREAD

**Issue by mathurinm** [EugeneNdiaye/Gap_Safe_Rules#15]
Because strong warm start is efficient, usually the pass of gap safe rules exits with 0 iteration:
this is a path with 10 alphas
```
Normal iter 0
Strong iter 100
Normal iter 0
Strong iter 220
Normal iter 0
Strong iter 170
Normal iter 0
Strong iter 280
Normal iter 0
Strong iter 430
Normal iter 0
Strong iter 910
Normal iter 0
Strong iter 1940
Normal iter 0
Strong iter 6490
Normal iter 0
Strong iter 19960
Normal iter 0

In [5]: n_iters                                                        
Out[5]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

Therefore, the n_iters return is always 0 in this case, which is not very informative, nor really true.

An easy solution would be that the returned  n_iter is the sum of the warm satart iter and the gsr iter. What do you think @EugeneNdiaye  ?

**Comment by EugeneNdiaye** [comment]
Yes: I will even remove the output of n_iters. 

I also noticed that the algo often converged with the pass strong rule + dynamic gap safe, but this is not guaranteed since the strong rule step is not safe.

**Comment by mathurinm** [comment]
Ok! I found it useful to debug but for other users it may indeed be useless
Thanks :+1:

**Comment by EugeneNdiaye** [comment]
I am preparing an update of the package, to simplify, harmonize some stuffs and potentially a simpler and better strong rules.

**Comment by mathurinm** [comment]
Cool, let me know if I can help for this
