### ISSUE TITLE
ENH: no need for asfortranarray on 1D array

### ISSUE THREAD

**Issue by mathurinm** [EugeneNdiaye/Gap_Safe_Rules#5]
there are multiple occurrences of `asfortranarray` called on a 1D array, 
eg
```
    Xbeta = np.asfortranarray(np.dot(X, beta_init))
    exp_Xbeta = np.asfortranarray(np.exp(Xbeta))
    residual = np.asfortranarray(y - exp_Xbeta / (1. + exp_Xbeta))
```

this is superfluous since these arrays are contiguous by default hence both C and Fortran.

it simplifies the code to remove these calls.

**Comment by EugeneNdiaye** [comment]
Not sure that default numpy array is contiguous. Will check where it is useless. Better keep it for safety.
