### ISSUE TITLE
BUG: clarify docstring/returns

### ISSUE THREAD

**Issue by mathurinm** [EugeneNdiaye/Gap_Safe_Rules#6]
alphas is defined in the return section of some `*_path` docstrings (lasso_path, logreg_path for example), but not returned

https://github.com/EugeneNdiaye/Gap_Safe_Rules/blob/master/lasso.py#L90
https://github.com/EugeneNdiaye/Gap_Safe_Rules/blob/master/lasso.py#L183

Automated docstring testing is possible but I've never done it

**Comment by EugeneNdiaye** [comment]
k
