### ISSUE TITLE
BUG: coefs shape don't match

### ISSUE THREAD

**Issue by mathurinm** [EugeneNdiaye/Gap_Safe_Rules#7]
In `_path` functions:
```
    coefs : array, shape (n_features, n_alphas)
        Coefficients along the path.
```

but the returned `betas` have transposed shape: `(n_alphas, n_features)`

`(n_features, n_alphas)` is sklearn compatible so I suggest we this and just return `betas.T`

**Comment by EugeneNdiaye** [comment]
fixed
