### ISSUE TITLE
ENH: possibility to disable linesearch for logreg CD

### ISSUE THREAD

**Issue by mathurinm** [EugeneNdiaye/Gap_Safe_Rules#8]
I don't know if the benefits of LS are clear: better step size, but at the cost of multiple evaluations of p_obj.

For my own benchmarks, I wanted to be able to use it or not, so i've implemented it on my branch `comparison`: 
https://github.com/mathurinm/Gap_Safe_Rules/commit/f15616a872dbf97d4cd00785517d8569887341d2

Once other PRs are merged, it is easy to implement and we only need to add a default parameter to `logreg_path`

**Comment by EugeneNdiaye** [comment]
linesearch removed. I need to check it more carefully ...
